
    create table tb_address (
       id int8 generated by default as identity,
        city_code int8 not null,
        complement varchar(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        district varchar(255),
        number int4 not null,
        post_code varchar(8) not null,
        street varchar(255) not null,
        updated_at timestamp,
        id_person int8 not null,
        primary key (id)
    );

    create table tb_contact (
       id int8 generated by default as identity,
        contact_type int4 not null,
        content varchar(255) not null,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        id_person int8 not null,
        primary key (id)
    );

    create table tb_document (
       id int8 generated by default as identity,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        document_type int4 not null,
        number varchar(50) not null,
        updated_at timestamp,
        id_person int8 not null,
        primary key (id)
    );

    create table tb_person (
       id int8 generated by default as identity,
        birthday date not null,
        civil_status integer default 1 not null,
        country_code_origin int4 not null,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        gender int4 not null,
        name varchar(255) not null,
        skin_color int4 not null,
        updated_at timestamp,
        primary key (id)
    );

    create table tb_relationship (
       id int8 generated by default as identity,
        bond_type int4 not null,
        relationship_type int4 not null,
        id_person int8 not null,
        id_person_parent int8 not null,
        primary key (id)
    );

    alter table if exists tb_address 
       add constraint UK_swvxifoe4eott5vqrnc0ng4ti unique (id_person);

    alter table if exists tb_address 
       add constraint FKhd7rk10ubgl08dcuqv19pjxwx 
       foreign key (id_person) 
       references tb_person;

    alter table if exists tb_contact 
       add constraint FKhodas27cdx069liitqfi9a4oh 
       foreign key (id_person) 
       references tb_person;

    alter table if exists tb_document 
       add constraint FK9wf2jbx580xeu6qyvfva7lnff 
       foreign key (id_person) 
       references tb_person;

    alter table if exists tb_relationship 
       add constraint FKmx7482tihedolhs3gkbinny19 
       foreign key (id_person) 
       references tb_person;

    alter table if exists tb_relationship 
       add constraint FK67rrb0e43nhtwk56d4siyh6x0 
       foreign key (id_person_parent) 
       references tb_person;
       
    create unique index numberx_document_type on tb_document (number,document_type);
    
    create unique index idpersonx_document_type on tb_document (id_person,document_type);
    
    create unique index contentx_contatct_type on tb_contact (content,contact_type);
    
    create unique index idpersonx_relationship_bound on tb_relationship(id_person,relationship_type,bond_type);
    
    create unique index idpersonx_relationship_parent on tb_relationship(id_person,id_person_parent);
