INSERT INTO TB_COUNTRY (NAME, ISO_CODE, ISO_CODE3, NUMBER_CODE, DIAL) VALUES ('Brasil', 'BR', 'BRA', 76, 55);
INSERT INTO TB_COUNTRY (NAME, ISO_CODE, ISO_CODE3, NUMBER_CODE, DIAL) VALUES ('United States', 'US', 'USA', 840, 1);

INSERT INTO TB_PERSON (NAME, BIRTHDAY, GENDER, SKIN_COLOR, ID_COUNTRY_ORIGIN) VALUES ('João Paulo Soares', '1984-01-26', 1, 3, 1);
INSERT INTO TB_PERSON (NAME, BIRTHDAY, GENDER, SKIN_COLOR, ID_COUNTRY_ORIGIN) VALUES ('Maria Bernardes da Silva', '1962-06-16', 1, 1, 1);
INSERT INTO TB_PERSON (NAME, BIRTHDAY, GENDER, SKIN_COLOR, ID_COUNTRY_ORIGIN) VALUES ('Teobaldo Souza da Silva', '1959-05-10', 1, 1, 1);

INSERT INTO TB_DOCUMENT (DOCUMENT_TYPE, NUMBER, ID_PERSON) VALUES (1, '67125926070',1);
INSERT INTO TB_DOCUMENT (DOCUMENT_TYPE, NUMBER, ID_PERSON) VALUES (1, '97933526047',2);
INSERT INTO TB_DOCUMENT (DOCUMENT_TYPE, NUMBER, ID_PERSON) VALUES (1, '65923050021',3);

INSERT INTO TB_RELATIONSHIP (ID_PERSON, ID_PERSON_PARENT, RELATIONSHIP_TYPE, BOND_TYPE) VALUES (1, 2, 2, 1);
INSERT INTO TB_RELATIONSHIP (ID_PERSON, ID_PERSON_PARENT, RELATIONSHIP_TYPE, BOND_TYPE) VALUES (1, 3, 1, 1);
INSERT INTO TB_RELATIONSHIP (ID_PERSON, ID_PERSON_PARENT, RELATIONSHIP_TYPE, BOND_TYPE) VALUES (2, 1, 3, 1);
INSERT INTO TB_RELATIONSHIP (ID_PERSON, ID_PERSON_PARENT, RELATIONSHIP_TYPE, BOND_TYPE) VALUES (3, 1, 3, 1);

INSERT INTO TB_CONTACT (CONTENT, CONTACT_TYPE, ID_PERSON) VALUES ('joao@teste.com.br',1,1);
INSERT INTO TB_CONTACT (CONTENT, CONTACT_TYPE, ID_PERSON) VALUES ('61987757662',2,1);