INSERT INTO TB_COUNTRY (NAME, ISO_CODE, ISO_CODE3, NUMBER_CODE, DIAL) VALUES ('Brasil', 'BR', 'BRA', 76, 55);
INSERT INTO TB_COUNTRY (NAME, ISO_CODE, ISO_CODE3, NUMBER_CODE, DIAL) VALUES ('United States', 'US', 'USA', 840, 1);

INSERT INTO TB_PERSON (NAME, BIRTHDAY, GENDER, SKIN_COLOR, ID_COUNTRY_ORIGIN) VALUES ('João Paulo Soares', '1984-01-26', 1, 3, 1);
INSERT INTO TB_PERSON (NAME, BIRTHDAY, GENDER, SKIN_COLOR, ID_COUNTRY_ORIGIN) VALUES ('Maria Bernardes da Silva', '1982-06-16', 1, 1, 1);

INSERT INTO TB_DOCUMENT (DOCUMENT_TYPE, NUMBER, ID_PERSON) VALUES (1, '76295508049',1);
INSERT INTO TB_DOCUMENT (DOCUMENT_TYPE, NUMBER, ID_PERSON) VALUES (1, '32465594060',2);
